openapi: 3.0.0
info:
  title: My App API
  version: 1.0.0
paths:
  /auth/login:
    post:
      operationId: authLogin
      summary: ログイン
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: ログイン成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
  /auth/logout:
    post:
      operationId: authLogout
      summary: ログアウト
      responses:
        '200':
          description: ログアウト成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
  /auth/signin:
    post:
      operationId: authSignin
      summary: サインイン
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: サインイン成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
  /auth/me:
    get:
      operationId: authMe
      summary: 認証情報取得
      responses:
        '200':
          description: 認証情報取得成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  me:
                    $ref: '#/components/schemas/AuthMe'
                    nullable: true
components:
  schemas:
    AuthMe:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        roles:
          type: array
          items:
            type: string
            enum:
              - user
              - admin
        lastLoginAt:
          type: string
          format: date
      required:
        - id
        - name
        - roles
        - lastLoginAt
