/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * 認証
 * OpenAPI spec version: 1.0.0
 */
import type { Arguments, Key } from "swr";
import useSWRMutation from "swr/mutation";
import type { SWRMutationConfiguration } from "swr/mutation";

export type AuthLoginBody = {
  email: string;
  password: string;
};

export type AuthLogin200 = {
  message: string;
};

export type AuthLogout200 = {
  message: string;
};

export type AuthSigninBody = {
  email: string;
  password: string;
};

export type AuthSignin200 = {
  message: string;
};

/**
 * @summary ログイン
 */
export type authLoginResponse200 = {
  data: AuthLogin200;
  status: 200;
};

export type authLoginResponseSuccess = authLoginResponse200 & {
  headers: Headers;
};
export type authLoginResponse = authLoginResponseSuccess;

export const getAuthLoginUrl = () => {
  return `/api/auth/login`;
};

export const authLogin = async (
  authLoginBody: AuthLoginBody,
  options?: RequestInit,
): Promise<authLoginResponse> => {
  const res = await fetch(getAuthLoginUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(authLoginBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: authLoginResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as authLoginResponse;
};

export const getAuthLoginMutationFetcher = (options?: RequestInit) => {
  return (_: Key, { arg }: { arg: AuthLoginBody }) => {
    return authLogin(arg, options);
  };
};
export const getAuthLoginMutationKey = () => [`/api/auth/login`] as const;

export type AuthLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof authLogin>>
>;
export type AuthLoginMutationError = Promise<unknown>;

/**
 * @summary ログイン
 */
export const useAuthLogin = <TError = Promise<unknown>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof authLogin>>,
    TError,
    Key,
    AuthLoginBody,
    Awaited<ReturnType<typeof authLogin>>
  > & { swrKey?: string };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getAuthLoginMutationKey();
  const swrFn = getAuthLoginMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary ログアウト
 */
export type authLogoutResponse200 = {
  data: AuthLogout200;
  status: 200;
};

export type authLogoutResponseSuccess = authLogoutResponse200 & {
  headers: Headers;
};
export type authLogoutResponse = authLogoutResponseSuccess;

export const getAuthLogoutUrl = () => {
  return `/api/auth/logout`;
};

export const authLogout = async (
  options?: RequestInit,
): Promise<authLogoutResponse> => {
  const res = await fetch(getAuthLogoutUrl(), {
    ...options,
    method: "POST",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: authLogoutResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as authLogoutResponse;
};

export const getAuthLogoutMutationFetcher = (options?: RequestInit) => {
  return (_: Key, __: { arg: Arguments }) => {
    return authLogout(options);
  };
};
export const getAuthLogoutMutationKey = () => [`/api/auth/logout`] as const;

export type AuthLogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof authLogout>>
>;
export type AuthLogoutMutationError = Promise<unknown>;

/**
 * @summary ログアウト
 */
export const useAuthLogout = <TError = Promise<unknown>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof authLogout>>,
    TError,
    Key,
    Arguments,
    Awaited<ReturnType<typeof authLogout>>
  > & { swrKey?: string };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getAuthLogoutMutationKey();
  const swrFn = getAuthLogoutMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary サインイン
 */
export type authSigninResponse200 = {
  data: AuthSignin200;
  status: 200;
};

export type authSigninResponseSuccess = authSigninResponse200 & {
  headers: Headers;
};
export type authSigninResponse = authSigninResponseSuccess;

export const getAuthSigninUrl = () => {
  return `/api/auth/signin`;
};

export const authSignin = async (
  authSigninBody: AuthSigninBody,
  options?: RequestInit,
): Promise<authSigninResponse> => {
  const res = await fetch(getAuthSigninUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(authSigninBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: authSigninResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as authSigninResponse;
};

export const getAuthSigninMutationFetcher = (options?: RequestInit) => {
  return (_: Key, { arg }: { arg: AuthSigninBody }) => {
    return authSignin(arg, options);
  };
};
export const getAuthSigninMutationKey = () => [`/api/auth/signin`] as const;

export type AuthSigninMutationResult = NonNullable<
  Awaited<ReturnType<typeof authSignin>>
>;
export type AuthSigninMutationError = Promise<unknown>;

/**
 * @summary サインイン
 */
export const useAuthSignin = <TError = Promise<unknown>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof authSignin>>,
    TError,
    Key,
    AuthSigninBody,
    Awaited<ReturnType<typeof authSignin>>
  > & { swrKey?: string };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getAuthSigninMutationKey();
  const swrFn = getAuthSigninMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
