/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * プロフィール
 * OpenAPI spec version: 1.0.0
 */
import axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";
import useSwr from "swr";
import type { Key, SWRConfiguration } from "swr";

export type ProfileRolesItem =
  (typeof ProfileRolesItem)[keyof typeof ProfileRolesItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProfileRolesItem = {
  user: "user",
  admin: "admin",
} as const;

export interface Profile {
  id: number;
  name: string;
  email: string;
  roles: ProfileRolesItem[];
  createdAt: string;
  updatedAt: string;
}

/**
 * @summary プロフィール取得
 */
export const getProfile = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<Profile>> => {
  return axios.get(`/api/profile`, options);
};

export const getGetProfileKey = () => [`/api/profile`] as const;

export type GetProfileQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProfile>>
>;
export type GetProfileQueryError = AxiosError<unknown>;

/**
 * @summary プロフィール取得
 */
export const useGetProfile = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof getProfile>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetProfileKey() : null));
  const swrFn = () => getProfile(axiosOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};
