/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * プロフィール
 * OpenAPI spec version: 1.0.0
 */
import useSwr from "swr";
import type { Key, SWRConfiguration } from "swr";

export type ProfileRolesItem =
  (typeof ProfileRolesItem)[keyof typeof ProfileRolesItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProfileRolesItem = {
  user: "user",
  admin: "admin",
} as const;

export interface Profile {
  id: number;
  name: string;
  email: string;
  roles: ProfileRolesItem[];
  createdAt: string;
  updatedAt: string;
}

/**
 * @summary プロフィール取得
 */
export type getProfileResponse200 = {
  data: Profile;
  status: 200;
};

export type getProfileResponseSuccess = getProfileResponse200 & {
  headers: Headers;
};
export type getProfileResponse = getProfileResponseSuccess;

export const getGetProfileUrl = () => {
  return `/api/profile`;
};

export const getProfile = async (
  options?: RequestInit,
): Promise<getProfileResponse> => {
  const res = await fetch(getGetProfileUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getProfileResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getProfileResponse;
};

export const getGetProfileKey = () => [`/api/profile`] as const;

export type GetProfileQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProfile>>
>;
export type GetProfileQueryError = Promise<unknown>;

/**
 * @summary プロフィール取得
 */
export const useGetProfile = <TError = Promise<unknown>>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof getProfile>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetProfileKey() : null));
  const swrFn = () => getProfile(fetchOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};
