/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * 認証
 * OpenAPI spec version: 1.0.0
 */
import axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";
import useSwr from "swr";
import type { Arguments, Key, SWRConfiguration } from "swr";
import useSWRMutation from "swr/mutation";
import type { SWRMutationConfiguration } from "swr/mutation";

export type AuthMeRolesItem =
  (typeof AuthMeRolesItem)[keyof typeof AuthMeRolesItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthMeRolesItem = {
  user: "user",
  admin: "admin",
} as const;

export interface AuthMe {
  id: number;
  name: string;
  roles: AuthMeRolesItem[];
  lastLoginAt: string;
}

export type AuthLoginBody = {
  email: string;
  password: string;
};

export type AuthLogin200 = {
  message: string;
};

export type AuthLogout200 = {
  message: string;
};

export type AuthSigninBody = {
  email: string;
  password: string;
};

export type AuthSignin200 = {
  message: string;
};

export type AuthMe200 = {
  /** @nullable */
  me?: AuthMe;
};

/**
 * @summary ログイン
 */
export const authLogin = (
  authLoginBody: AuthLoginBody,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<AuthLogin200>> => {
  return axios.post(`/api/auth/login`, authLoginBody, options);
};

export const getAuthLoginMutationFetcher = (options?: AxiosRequestConfig) => {
  return (_: Key, { arg }: { arg: AuthLoginBody }) => {
    return authLogin(arg, options);
  };
};
export const getAuthLoginMutationKey = () => [`/api/auth/login`] as const;

export type AuthLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof authLogin>>
>;
export type AuthLoginMutationError = AxiosError<unknown>;

/**
 * @summary ログイン
 */
export const useAuthLogin = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof authLogin>>,
    TError,
    Key,
    AuthLoginBody,
    Awaited<ReturnType<typeof authLogin>>
  > & { swrKey?: string };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getAuthLoginMutationKey();
  const swrFn = getAuthLoginMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary ログアウト
 */
export const authLogout = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<AuthLogout200>> => {
  return axios.post(`/api/auth/logout`, undefined, options);
};

export const getAuthLogoutMutationFetcher = (options?: AxiosRequestConfig) => {
  return (_: Key, __: { arg: Arguments }) => {
    return authLogout(options);
  };
};
export const getAuthLogoutMutationKey = () => [`/api/auth/logout`] as const;

export type AuthLogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof authLogout>>
>;
export type AuthLogoutMutationError = AxiosError<unknown>;

/**
 * @summary ログアウト
 */
export const useAuthLogout = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof authLogout>>,
    TError,
    Key,
    Arguments,
    Awaited<ReturnType<typeof authLogout>>
  > & { swrKey?: string };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getAuthLogoutMutationKey();
  const swrFn = getAuthLogoutMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary サインイン
 */
export const authSignin = (
  authSigninBody: AuthSigninBody,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<AuthSignin200>> => {
  return axios.post(`/api/auth/signin`, authSigninBody, options);
};

export const getAuthSigninMutationFetcher = (options?: AxiosRequestConfig) => {
  return (_: Key, { arg }: { arg: AuthSigninBody }) => {
    return authSignin(arg, options);
  };
};
export const getAuthSigninMutationKey = () => [`/api/auth/signin`] as const;

export type AuthSigninMutationResult = NonNullable<
  Awaited<ReturnType<typeof authSignin>>
>;
export type AuthSigninMutationError = AxiosError<unknown>;

/**
 * @summary サインイン
 */
export const useAuthSignin = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof authSignin>>,
    TError,
    Key,
    AuthSigninBody,
    Awaited<ReturnType<typeof authSignin>>
  > & { swrKey?: string };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getAuthSigninMutationKey();
  const swrFn = getAuthSigninMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary 認証情報取得
 */
export const authMe = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<AuthMe200>> => {
  return axios.get(`/api/auth/me`, options);
};

export const getAuthMeKey = () => [`/api/auth/me`] as const;

export type AuthMeQueryResult = NonNullable<Awaited<ReturnType<typeof authMe>>>;
export type AuthMeQueryError = AxiosError<unknown>;

/**
 * @summary 認証情報取得
 */
export const useAuthMe = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof authMe>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getAuthMeKey() : null));
  const swrFn = () => authMe(axiosOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};
